# These are supported funding model platforms

github: [iamthonifhomuhali] # Up to 4 GitHub Sponsors usernames
patreon: ytai
open_collective: ytai
ko_fi: ytai
tidelift: npm/ytai-cli
community_bridge: ytai-media-intelligence-lab
liberapay: ytai
issuehunt: ytai
lfx_crowdfunding: ytai-media-intelligence-lab
polar: ytai
buy_me_a_coffee: ytai
thanks_dev: ytai
custom: 
  - https://ytai.ai/sponsor
  - https://muhalilabs.com/support

